CXX		=	g++
CXXFLAGS	= -O3 -DNDEBUG -fpermissive -g -w -std=c++11 -Wall -Lc:\mingw\lib -Ic:\mingw\include -D_WIN32_WINNT=0x0601 -DWINVER=0x0601 -DMSVCRT_VERSION=710

NLIB		=	-lws2_32 -lboost_log-mgw48-mt-d-1_55 -lboost_date_time-mgw48-mt-d-1_55 -lboost_regex-mgw48-mt-d-1_55 -lboost_log_setup-mgw48-mt-d-1_55 -lboost_chrono-mgw48-mt-d-1_55 -lboost_system-mgw48-mt-d-1_55 -lboost_filesystem-mgw48-mt-d-1_55 -lboost_iostreams-mgw48-mt-d-1_55 -lboost_thread-mgw48-mt-d-1_55
	
#  /usr/local/lib/libboost_filesystem-mt.dll.a /usr/local/lib/libboost_iostreams-mt.dll.a /usr/local/lib/libboost_thread-mt.dll.a /usr/local/lib/libboost_iostreams-mt.dll.a

BIN=promoCalculator

SRC=$(wildcard *.cpp)
OBJ=$(SRC:%.cpp=%.o)

all: $(OBJ)
	$(CXX) $(CXXFLAGS) -o $(BIN) $^ $(NLIB)

%.o: %.c
	$(CXX) $@ -c $<

clean:
	rm -f *.o
	rm $(BIN)

	