CXX		=	g++
CXXFLAGS	=	-g -O0 -fno-inline -w -std=c++11 -Wall -L/lib -I/usr/include 
NLIB		=	-lboost_system-mt -lboost_filesystem-mt -lboost_iostreams-mt -lboost_thread-mt -lboost_log-mt -lboost_date_time-mt -lboost_regex-mt -lboost_log_setup-mt -lboost_chrono-mt

BIN=promoCalculatorDbg

SRC=$(wildcard *.cpp)
SRC-FILES=$(filter-out stdafx.cpp, $(SRC))

OBJ=$(SRC-FILES:%.cpp=%.o)

all: $(OBJ)
	$(CXX) $(CXXFLAGS) -o $(BIN) $^  $(NLIB)

%.o: %.c
	$(CXX) $@ -c $<

clean:
	rm -f *.o
	rm $(BIN)

